### ISSUE TITLE
Rollup does not rebuild when adding a new JS file

### ISSUE THREAD

**Issue by billcolumbia** [billcolumbia/docker-node-build-system#2]
- Up the containers
- Create a new JS file in `src/js/modules`
- It does not get built into dist

**Comment by friartuck6000** [comment]
See [build/system/rollup.js#L43-L52](../blob/d8a27f2225a75a45ca8ae048451240f0bc027d40/build-system/rollup.js#L43-L52).

The config file is globbing existing files and only exporting configs for those, so Rollup won't know about files added after the fact unless they're imported by an existing file.
